app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lucky_number:
    path:     /lucky/number/{count}
    defaults: { _controller: AppBundle:Lucky:number, count: 1 }

lucky_apiNumber:
    path:     /api/lucky/number
    defaults: { _controller: AppBundle:Lucky:apiNumber }